
#=============  Makefile of SUB Directory =============
#== exits in 24/memo 24/calendar 24/main repectively ==


OBJECTS  = $(patsubst %.c, %.o, $(wildcard *.c))	 
CFLAGS  = -I ../include

all : $(OBJECTS)			
	cp -f $^ ../			
					
clean :
	rm -rf *.o

	
	
	
	
	
